
name: cicd to EC2

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.properties
        run: |
          mkdir -p backend/Union-Project/src/main/resources
          cat > backend/Union-Project/src/main/resources/application.properties << 'EOF'
          spring.application.name=union
          spring.datasource.url=${{ secrets.DB_URL }}
          spring.datasource.username=${{ secrets.DB_USER }}
          spring.datasource.password=${{ secrets.DB_PASSWORD }}
          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
          spring.jpa.hibernate.ddl-auto=update

          spring.jpa.show-sql=true
          spring.jpa.properties.hibernate.format_sql=true
          logging.level.org.hibernate.SQL=DEBUG
          spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

          server.address=0.0.0.0
          server.ssl.enabled=false

          spring.servlet.multipart.enabled=true
          spring.servlet.multipart.max-file-size=50MB
          spring.servlet.multipart.max-request-size=50MB
          logging.level.org.springframework.web=DEBUG
          logging.level.org.springframework.web.multipart=DEBUG

          file.upload-dir=/home/ubuntu/uploads
          EOF

      - name: Build with Gradle
        run: |
          cd backend/Union-Project
          chmod +x gradlew
          ./gradlew clean build -x test --stacktrace

      - name: cicd to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/Union-Project/build/libs/union-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/"
          overwrite: true
          timeout: "60s"
          strip_components: 0


      - name: Run App on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop union.service || true
            sudo systemctl daemon-reload
            sudo systemctl start union.service